# Exercícios de Python caderno TEC

## Exercício 1

Um desenvolvedor de software escreveu o programa a seguir, usando Python:
 
def funcao (X):
       if (X==1): return (1)
       else: return ( X + funcao (X-2) )


X = int ( input (‘Valor X = ’) )
print (‘ Resultado = ‘, funcao (X) )
 

Caso seja passado como valor de X o número 27, o resultado apresentado será:

In [1]:
#Questões sobre python

def funcao (X):
       if (X==1): return (1)
       else: 
           print(X)
           return ( X + funcao (X-2) )


X = int ( input ('Valor X = ') )
print('Resultado = ', funcao(X))

# Funcionamento: caso a entrada seja 27, ele irá somar sempre o valor X com um valor 2 dígitos menor
# 27+25+23+21+19+17+15+13+11+9+7+5+3 = 196

27
25
23
21
19
17
15
13
11
9
7
5
3
Resultado =  196


## Exercício 2

Analise o trecho código Python a seguir.
 
AREA = [3.7, 5.356, 4.9061, 4.32092, 9.038758, 32.5434846]
 
resultado = list(map(round, AREA, range(1,5))) print(resultado)
 
O valor impresso é:

In [4]:
AREA = [3.7, 5.356, 4.9061, 4.32092, 9.038758, 32.5434846]
print(AREA)
 
resultado = list(map(round, AREA, range(1,5))) 
print(resultado)

[3.7, 5.356, 4.9061, 4.32092, 9.038758, 32.5434846]
[3.7, 5.36, 4.906, 4.3209]


In [3]:
a = 6.878293
round(a)

7

## Exercício 3

In [6]:
# Funções de vatores

numeros = [1, 3, 4, 5]
numeros.append(9)
print(numeros)

[1, 3, 4, 5, 9]


## Exercício 4 formatação

In [10]:
x = 2.467383
round(x, 0)

print("{:.1f}".format(12.45667))

12.5


## NUMPY

In [1]:
import numpy as np

In [5]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
# 5 linhas 4 colunas
b = a.reshape((5, 4))
print(b)

# 4 linhas 5 colunas
b = a.reshape((4, 5))
print(b)

np.reshape(a, (4,5))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])