In [2]:
import numpy as np

# Numpy Introduction

Biblioteca de vetores multidimensionais, é mais rápida que uma lista (mais rápida para ler menos bytes). Numpy usa tipos fixos. Listas guardam bem mais informação para um simples numero inteiro, por exemplo. Numpy guarda apenas o binário em Int32 (ou outro tipo). Em listas, você tem mais de um tipo de variável, então seria necessário ficar verificando se é inteiro ou não. No numpy isso não é necessário. Numpy tem uma memória em sequencia, não pulamos blocos de memória.

Diferença entre Numpy e listas: numpy tem mto mais funções do que as listas disponibilizam.
Aplicações do numpy: MATLAB (operações matemáticas poderosas, gráficos, backend pandas), ML aplicações

In [3]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0, 8.0, 7.0], [1.2, 3.5, 6.1]])

# Dimension
print(b.ndim)

2


In [7]:
# Shape
a.shape
b.shape

(2, 3)

In [17]:
# Get type
a.dtype

# Change de Type
a = np.array([1, 2, 3], dtype='int16')
a.dtype

dtype('int16')

In [19]:
# Get size in bytes. So, if the type is int16, the result will be 2. If int32, the size will be 4
a.itemsize

# To see the number of elements, we use
a.size

3

# Acessing/Changing specific elements, rows, colums etc.

In [19]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [9]:
a.shape

(2, 7)

In [10]:
# Get specifc element [row, column]. The rows and columns start on 0

a[1, 5] # 13
a[0, 5] # 6
a[1, -2] # 13

np.int64(13)

In [21]:
# Get a specific row
a[0]
a[0, -5]

np.int64(3)

In [12]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [25]:
# Fancier now
# Between 2 and 6 elements
a[0, 1:6]
a[0, 0:89] # Não da erro mesmo o último elemento sendo o de número 7

# Skiping elements
# a[0, 1:6:2] # 2, 4, 6

array([1, 2, 3, 4, 5, 6, 7])

In [14]:
# Change a number in a specific position
a[1, 5] = 30
print(a)

# Quero que, em todas as linhas, a posição 2 (elemento 3) mude para o valor estipulado
a[:, 2] = 5
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 30 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 30 14]]


In [15]:
# 3-D Example

b = np.array([[[1, 2], [3, 4]], 
              [[5, 6], [6, 7]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [6 7]]]


In [16]:
# Elemento específico de um array 3D
# Quero o elemento 4 

# b[conjunto, linha, coluna]
b[0, 1, 1]

np.int64(4)

In [17]:
# REPLACE

b[1, 1, 0] = 88
print(b)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [88  7]]]


In [18]:
b[:, 1, :] = [[9,9], [8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


# Initializing diferent types of arrays

In [ ]:
# All 0s matrix
np.zeros((2,3))

# All 1s matrix
np.ones((4,2,2), dtype='int32')

# Any other number
np.full((2,2), 99)

# Any other number (full_like)
np.full_like(a, 4)

# Random Integer values
np.random.randint(-4,8, size=(3,3))

# Repeat an array

arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

In [64]:
a = np.ones((5, 5))
print(a)

z = np.zeros((3, 3))
print(z)

z[1, 1] = 9
print(z)

a[1:4, 1:4] = z
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# Be careful when copying arrays!!!

In [ ]:
# Se você copiar arrays desta forma, os arrays ficarão conectados e se modificarão juntos
a = np.array([1, 2, 3, 4])
print(a)
b = a
a[0] = 66
print(a)
print(b)

[1 2 3 4]
[66  2  3  4]
[66  2  3  4]


In [68]:
# Forma correta
a = np.array([1, 2, 3])
b = a.copy()
print(a)
print(b)

b[0] = 100
print(b)
print(a)

[1 2 3]
[1 2 3]
[100   2   3]
[1 2 3]


In [56]:
# Se você copiar arrays desta forma, os arrays ficarão conectados e se modificarão juntos
a = np.array([1, 2, 3, 4])
print(a)
b = a
a[0] = 66
print(a)
print(b)

[1 2 3 4]
[66  2  3  4]
[66  2  3  4]


# Mathematics

In [50]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [44]:
a+2

array([3, 4, 5])

In [45]:
a-2

array([-1,  0,  1])

In [46]:
a*2

array([2, 4, 6])

In [51]:
b = np.array([1, 0, 1, 0])
a+b

array([2, 2, 4, 4])

In [52]:
a**2

array([ 1,  4,  9, 16])

In [54]:
# Seno dos valores
np.sin(a)
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

# Linear Algebra

In [71]:
# Multiplicando matrizes multidimensionais. A linhas de uma devem ser a mesma quantidade das colunas da outra

a = np.ones((2, 3))
b = np.full((3, 2), 2)

print(a);print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [74]:
# Determinante da matriz

# Criei uma matriz de inteiros aleatórios para testar
c = np.random.randint(1, 5, size = (3,3))
print(c)
np.linalg.det(c)

[[4 1 2]
 [1 2 4]
 [2 1 1]]


np.float64(-6.999999999999999)

# Statistics


In [75]:
stats = np.array([[1, 2, 3],[4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [78]:
np.min(stats)
# Para cada linha
np.min(stats, axis=1)
# Para cada coluna (no caso me retorna a primeira linha pois ela tem os menores valores de coluna também)
np.min(stats, axis=0)

array([1, 2, 3])

In [81]:
np.max(stats)


np.int64(6)

In [84]:
# Soma todos
np.sum(stats)

# Soma linha por linha
np.sum(stats, axis=1)

# Soma coluna por coluna
np.sum(stats, axis=0)

array([5, 7, 9])

# Reorganizing arrays

In [88]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before.shape)

after = before.reshape(8,1)
print(after)

after = before.reshape((2,2,2))
print(after)

(2, 4)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [90]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [91]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

# Parantesis e braquets funcionam []
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Miscellaneous

## Load data from file

In [93]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata.astype('int32')

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

## Boolean Masking and Advaced indexing

In [94]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [95]:
filedata[filedata>50]

array([196.,  75., 766.,  75.,  55., 999.,  78.,  76.,  88.])

In [97]:
## You can index with a list in Numpy
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
# Números nas posições 1, 2, e 8
a[[1,2,8]]

array([2, 3, 9])

In [99]:
# Colunas com valores maiores do que 50
np.all(filedata > 50, axis=0)

# Linha com valores maiores do que 50
np.all(filedata > 50, axis=1)

array([False, False, False])

In [102]:
(~(filedata > 50) & (filedata < 100))

array([[ True,  True,  True,  True, False, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

# [Important Functions](https://medium.com/@chuntcdj/numpy-the-10-functions-that-you-should-know-bee7f53c98cf)


In [3]:
# Linspace: números reais


# Número em que vai começar, número que vai terminar, números a serem gerados
np.linspace(10,100,10)

np.linspace(1999, 300000)

array([  1999.        ,   8080.65306122,  14162.30612245,  20243.95918367,
        26325.6122449 ,  32407.26530612,  38488.91836735,  44570.57142857,
        50652.2244898 ,  56733.87755102,  62815.53061224,  68897.18367347,
        74978.83673469,  81060.48979592,  87142.14285714,  93223.79591837,
        99305.44897959, 105387.10204082, 111468.75510204, 117550.40816327,
       123632.06122449, 129713.71428571, 135795.36734694, 141877.02040816,
       147958.67346939, 154040.32653061, 160121.97959184, 166203.63265306,
       172285.28571429, 178366.93877551, 184448.59183673, 190530.24489796,
       196611.89795918, 202693.55102041, 208775.20408163, 214856.85714286,
       220938.51020408, 227020.16326531, 233101.81632653, 239183.46938776,
       245265.12244898, 251346.7755102 , 257428.42857143, 263510.08163265,
       269591.73469388, 275673.3877551 , 281755.04081633, 287836.69387755,
       293918.34693878, 300000.        ])

In [4]:
# Arange: mesma coisa do linspace mas com números insteiros
np.arange(200, 800, 9)

array([200, 209, 218, 227, 236, 245, 254, 263, 272, 281, 290, 299, 308,
       317, 326, 335, 344, 353, 362, 371, 380, 389, 398, 407, 416, 425,
       434, 443, 452, 461, 470, 479, 488, 497, 506, 515, 524, 533, 542,
       551, 560, 569, 578, 587, 596, 605, 614, 623, 632, 641, 650, 659,
       668, 677, 686, 695, 704, 713, 722, 731, 740, 749, 758, 767, 776,
       785, 794])

In [10]:
np.random.seed(22)

np.random.randint(10, size=(5,7,8))

array([[[5, 4, 0, 4, 6, 6, 4, 8],
        [4, 2, 8, 7, 2, 9, 8, 8],
        [5, 4, 2, 2, 1, 6, 9, 3],
        [3, 2, 7, 7, 7, 7, 9, 4],
        [4, 7, 1, 1, 7, 3, 9, 0],
        [1, 5, 5, 9, 9, 4, 1, 4],
        [3, 3, 4, 0, 2, 3, 6, 0]],

       [[7, 9, 5, 0, 5, 8, 1, 8],
        [8, 3, 1, 5, 6, 5, 6, 9],
        [2, 5, 6, 0, 5, 1, 1, 2],
        [9, 9, 0, 3, 5, 7, 6, 1],
        [8, 4, 8, 9, 8, 5, 5, 5],
        [4, 4, 3, 0, 8, 4, 0, 1],
        [5, 6, 8, 2, 6, 5, 6, 6]],

       [[7, 7, 4, 4, 8, 1, 2, 3],
        [6, 0, 3, 9, 3, 6, 9, 6],
        [4, 8, 7, 1, 3, 7, 1, 1],
        [6, 2, 8, 5, 0, 8, 1, 6],
        [9, 0, 3, 5, 9, 0, 7, 2],
        [6, 9, 6, 8, 6, 5, 3, 3],
        [2, 2, 7, 9, 0, 6, 8, 6]],

       [[8, 6, 6, 6, 5, 5, 9, 3],
        [6, 2, 7, 7, 3, 2, 2, 2],
        [9, 8, 0, 5, 8, 7, 7, 7],
        [7, 2, 1, 6, 9, 0, 9, 0],
        [0, 4, 2, 5, 4, 6, 8, 5],
        [1, 9, 1, 1, 5, 5, 9, 9],
        [5, 1, 7, 1, 0, 2, 3, 3]],

       [[1, 5, 4, 0, 8, 1, 6, 1],
      

In [17]:
# Transposição de vetores
array = np.random.randint(4,99, (13, 2))
print(array)

np.transpose(array)


[[51 83]
 [58 54]
 [54 57]
 [94 41]
 [86 45]
 [37 65]
 [98 11]
 [18 58]
 [56 94]
 [68 29]
 [12 81]
 [13 50]
 [91 65]]


array([[51, 58, 54, 94, 86, 37, 98, 18, 56, 68, 12, 13, 91],
       [83, 54, 57, 41, 45, 65, 11, 58, 94, 29, 81, 50, 65]])

# Misturando matrizes

In [25]:
a = np.ones([5,5])
print(a)

b = np.zeros([3,3])
print(b)
b[1,1] = 9
print(b)

a[1:4,1:4] = b
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
